### ISSUE TITLE
Package "types" pointing at full TS source code instead of declarations

### ISSUE THREAD

**Issue by eric-parsons** [wojtekmaj/merge-refs#25]
Hi,

I just noticed an issue with the latest version of this module. In package.json, it has `"types": "src/index.ts"`. However, this should point to one of the `*.d.ts` files instead, e.g. `"dist/esm/index.d.ts"`. Or alternatively, it could probably just  be removed as I'm pretty sure TypeScript will pick up the `*.d.ts` files automatically that are sitting next to corresponding `*.js` files.

The reason this is an issue for me is that pointing `types` at `index.ts` appears to be causing TypeScript to compile your source code with my project's settings. Since I am using the `importsNotUsedAsValues` setting in my tsconfig.json, it complains about the React import, since it should be `import type * as React from 'react';` according to my settings. The `skipLibCheck` setting doesn't appear to help in this case -- I guess it only affects declaration files.

Happy to see though that this library will now have types. Thanks @Skona27!

**Comment by aspirisen** [comment]
I faced the same issue

**Comment by wojtekmaj** [comment]
I think I copied this setting from Reach UI:
https://github.com/reach/reach-ui/blob/dev/packages/alert/package.json
I think they had some good reason to do this and I aim to have identical or at least similar configs in all OSS packages I maintain because I severely lack time to maintain them. So I guess the way to go would be to change the imports rather than package.json types field 🤔

**Comment by aspirisen** [comment]
I think there should be a declaration emit during typescript build, and in package.json set the emmited declaration in `types` field
<img width="289" alt="image" src="https://user-images.githubusercontent.com/3620639/215323739-08136bb1-6b04-43bb-8354-d9d8b086c895.png">

**Comment by eric-parsons** [comment]
Thanks for the fix @wojtekmaj. This fixes my immediate issue, however the `import type` issue was just an example of what can go wrong if the person using the package had different tsconfig.json settings. I understand having little time (boy do I ever!) and wanting to keep things consistent, however you might still want to consider at some point changing all of your projects' `"types"` property to point at `"dist/cjs/index.js"` or whatever path is appropriate based on the path of `"main"`. The [TypeScript docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) clearly indicate the intent for this property to point at a declarations file and not a source file. Otherwise, slight variations of this issue might pop up again in the future for others.

**Comment by wojtekmaj** [comment]
Fixed that fully in 1.1.2 :)
