### ISSUE TITLE
Generic input type unknown for mergeRefs function

### ISSUE THREAD

**Issue by smellai** [wojtekmaj/merge-refs#81]
I think there may be some issue with the type definition,
if I do:
`ref={mergeRefs([ref1, ref2])}`

I get:
`argument of type 'Ref<HTMLInputElement>[]' not assignable to parameter of type 'Ref<unknown> | undefined'`

![Screenshot 2023-04-14 alle 15 39 03](https://user-images.githubusercontent.com/1763268/232059328-f2f012af-3dee-444f-8a55-40480f2f93f6.png)

**Comment by wojtekmaj** [comment]
```diff
-ref={mergeRefs([ref1, ref2])}
+ref={mergeRefs(ref1, ref2)}
```
